### ISSUE TITLE
Lista 

### ISSUE THREAD

**Issue by Misael-Micciche-JCMaxwell-5Ai** [Misael-Micciche-JCMaxwell-5Ai/Java-Sockets#10]
Sul server non viene aggiornata la lista delle operazioni

**Comment by Mirko-Checchia-JCMaxwell-5Ai** [comment]
Ho aggiunto il comando System.out in modo da mostrare sul server la lista di operazioni dell'utente

**Comment by Misael-Micciche-JCMaxwell-5Ai** [comment]
Grazie

**Comment by Misael-Micciche-JCMaxwell-5Ai** [comment]
Ciao Mirko! Forse ci siamo capiti male, bisognava aggiornare ad ogni operazione, hai voglia di ricontrollare e correggere?

**Comment by Veronica-De-Santis-JCMaxwell-5Ai** [comment]
Corretto in parte. Mancano i "System.out.println" sui vari metodi

**Comment by Misael-Micciche-JCMaxwell-5Ai** [comment]
Coorretto
