### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by Misael-Micciche-JCMaxwell-5Ai** [Misael-Micciche-JCMaxwell-5Ai/Java-Sockets#13]
Ragazzi testando il software ho notato questi problemi:

- Bisogna aggiungere gli spazi tra Nickname e frase nel server 
- Aggiunta stringa "-Nickname- crea -NomeGruppo-" (uso comando New)
- Aggiunta stringa "i gruppi esistenti sono" -prima di Group 1: NomeGruppo- (uso comando Join)
- Correggere join controllando la stampa del server (vari errori)
- Togliere stampa lista gruppi dopo benvenuto (Join) e nel server la richiesta
- Durante la normale conversazione ce una stampa nel server

**Comment by Mirko-Checchia-JCMaxwell-5Ai** [comment]
Ho risolto i primi 3 problemi, per gli altri non riesco a capire che errore ci sia nel join che stampa nel server anche quando non dovrebbe...
ho notato anche che quando sbagliamo a inserire il nome del gruppo nel join, ci dice che non esiste tale gruppo, ma poi non ci fa inserire un altro nome di gruppo a cui aggiungersi; piuttosto ci fa mandare messaggi a caso nel server...ci sarà da risolvere anche questa cosa
                                                                                                                                     ~ Mirkus ~

**Comment by Veronica-De-Santis-JCMaxwell-5Ai** [comment]
AGGIORNAMENTO PROBLEMI:

- Correggere join controllando la stampa del server (vari errori)
- Togliere la stampa lista gruppi dopo benvenuto (Join) e nel server la richiesta
- Stampa doppia
- Aggiungere una stringa che dica al Client che ha creato un nuovo gruppo
- Controllare l'inserimento di un nome sbagliato nel Join

**Comment by Veronica-De-Santis-JCMaxwell-5Ai** [comment]
AGGIORNAMENTO PROBLEMI:

- Stampa doppia
- Aggiungere una stringa che dica al Client che ha creato un nuovo gruppo
- Controllare l'inserimento di un nome sbagliato nel Join
- Inviare la notifica di accesso agli altri utenti

**Comment by Veronica-De-Santis-JCMaxwell-5Ai** [comment]
AGGIORNAMENTO PROBLEMI:

- Controllare l'inserimento di un nome sbagliato nel Join
- Inviare la notifica di accesso agli altri utenti
- Correggere la stampa nel gruppo
- Inserire un metodo per uscire dal gruppo ma non da tutto il programma

**Comment by Misael-Micciche-JCMaxwell-5Ai** [comment]
AGGIORNAMENTO PROBLEMI:

- Inserire un metodo per uscire dal gruppo ma non da tutto il programma

**Comment by Misael-Micciche-JCMaxwell-5Ai** [comment]
AGGIORNAMENTO PROBLEMI:

- Inserire un metodo per uscire dal gruppo ma non da tutto il programma (Quit)
- Inserire un metodo per invitare un utente ad un gruppo (Invite)

**Comment by Mirko-Checchia-JCMaxwell-5Ai** [comment]
AGGIORNAMENTO PROBLEMI:

- Inserire un metodo per invitare un utente ad un gruppo (Invite)

**Comment by Misael-Micciche-JCMaxwell-5Ai** [comment]
Problemi risolti!
